### ISSUE TITLE
Add AppSettings Configuration ability

### ISSUE THREAD

**Issue by masanek2** [serilog-contrib/serilog-sinks-splunk#148]
The logic to allow for easy appsettings configuration doesn't work with complex types. Its easy enough to add this extension to my own assembly but wonder if it should be provided by default

        public static LoggerConfiguration Splunk(this LoggerSinkConfiguration sinkConfiguration, string host, int port)
        {
            return sinkConfiguration.SplunkViaTcp(new Serilog.Sinks.Splunk.SplunkTcpSinkConnectionInfo(host, port));
        }

Or maybe im doing something wrong ha!

**Comment by merbla** [comment]
Closing as a part of larger Serilog contrib reorg

Checkout serilog/serilog#1627
