### ISSUE TITLE
"Could not load file or assembly 'Splunk.Logging.Common', Version 1.0.0.0...."

### ISSUE THREAD

**Issue by jamesSampica** [serilog-contrib/serilog-sinks-splunk#155]
I've got a .net framework v4.6.2 console app that I'm trying to configure splunk tcp v1.5 with.

I installed the package and configured it using the following code...
```
var log = new LoggerConfiguration()
                .WriteTo.SplunkViaTcp(
                    new Serilog.Sinks.Splunk.SplunkTcpSinkConnectionInfo("127.0.0.1", 10001),
                    restrictedToMinimumLevel: LevelAlias.Minimum,
                    formatProvider: null,
                    renderTemplate: true)
                .CreateLogger();

log.Information("Hello World");
```

it builds/runs but at runtime I get the following exception...

```
 System.IO.FileLoadException
HResult=0x80131044
Message=Could not load file or assembly 'Splunk.Logging.Common, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)
Source=Serilog.Sinks.Splunk.TCP
StackTrace:
at Serilog.Sinks.Splunk.TcpSink..ctor(SplunkTcpSinkConnectionInfo connectionInfo, ITextFormatter formatter)
at Serilog.LoggerConfigurationSplunkExtensions.SplunkViaTcp(LoggerSinkConfiguration loggerConfiguration, SplunkTcpSinkConnectionInfo connectionInfo, LogEventLevel restrictedToMinimumLevel, IFormatProvider formatProvider, Boolean renderTemplate)
at ConsoleApp1.Program.Main(String[] args)
```

If I downgrade to Serilog.Sinks.Splunk.TCP v1.2 this does not throw, but v1.4 and v1.5 both throw.

I've attached a repro solution of this to this issue.

[ConsoleApp1.zip](https://github.com/serilog/serilog-sinks-splunk/files/7959448/ConsoleApp1.zip)

**Comment by EEParker** [comment]
If this issue is still relevant, please comment or reopen.

**Comment by ipetrouchtchak-fi** [comment]
As far a I can tell, this is still an issue.

**Comment by EEParker** [comment]
Thanks for the feedback, I was able to replicate with a unit test and will prioritize it.
![image](https://github.com/serilog-contrib/serilog-sinks-splunk/assets/15874076/448dc429-94bc-4f61-b5dc-7443b090125c)

**Comment by VictorioBerra** [comment]
Thank you for the repro 🙏 @jamesSampica

**Comment by EEParker** [comment]
I've been working through this on a branch and it seems to be related to assembly signing and the upstream splunk library not being signed.
