### ISSUE TITLE
EventCollector should support HttpClientHandler for ServerCertificateValidationCallback

### ISSUE THREAD

**Issue by vinayp0812** [serilog-contrib/serilog-sinks-splunk#158]
We don't want bypass certificate validation on global level. Please provide the support for handling this to specific http request.

Please find the below snippet for with serilog -

Log.Logger = new LoggerConfiguration().Enrich.WithProperty("RequestId", _requestId).Enrich.WithProperty("Environment", _environment)
.MinimumLevel.Information()
.WriteTo.Console()
.WriteTo.EventCollector("xyz", "abc", source: "Machine", sourceType: "sourceApp1", host: "AWS Lambda", index: "appIndex")
.CreateLogger();

**Comment by EEParker** [comment]
This can be handled with the HttpMessageHandler parameter of `.WriteTo.EventCollector`
