### ISSUE TITLE
Is there any option to set http timeout for Collector

### ISSUE THREAD

**Issue by joseviniciusnunes** [serilog-contrib/serilog-sinks-splunk#164]
Hi guys

Testing in my application I realized that if the splunk presents instability, the .dispose() is waiting forever.

A timeout option would be appreciated, thanks!

**Comment by jpfifer** [comment]
If you need a short term approach installing an `HttpMessageHandler` at log creation time would allow you to effectively set a timeout by creating a cancellation token with a fixed time.

**Comment by EEParker** [comment]
@jpfifer has listed current solution correct, e.g. HttpMessageHandler parameter of `.WriteTo.EventCollector`.
