### ISSUE TITLE
Appveyor/Nuget Package Release

### ISSUE THREAD

**Issue by EEParker** [serilog-contrib/serilog-sinks-splunk#173]
@merbla Is the appveyor build still set up to work on the master branch? Is there anything further that needs to be done to push this to nuget other than merging changes into master? Thank you for your time.

**Comment by nblumhardt** [comment]
Hi @EEParker @VictorioBerra; I'll help coordinate getting this back in action. Just checking in with Augusto on the best way to do this, I'll loop back shortly.

**Comment by nblumhardt** [comment]
Howdy again; I think the right way forward with this is to migrate to GitHub Actions; I should be able to send a PR in the next few days.

**Comment by EEParker** [comment]
Thank you for the update.
